core/urls.py
from unicodedata import name
from django.urls import path, re_path
from core.api import add_region, add_season

from core.models import Region, Season
from . import web

app_name = "core"
urlpatterns = [
    path("", web.Dashboard.index, name="dashboard"),
    path("seasons", web.Season.get_seasons, name="seasons"),
    path("add-season", web.Season.add_season, name="add-season"),
    path("add-region", web.Region.add_region, name="add-region"),
    path("regions", web.Region.get_regions, name="regions"),
    path("inactive-regions", web.Region.get_inactive_regions, name="inactive_regions"),
    re_path(
        r"^edit-region/(?P<region_id>[\w-]+)/$",
        web.Region.edit_region,
        name="edit-region",
    ),
    re_path(
        r"^delete-region/(?P<region_id>[\w-]+)/$",
        web.Region.delete_region,
        name="delete-region",
    ),
    path(
        "add-constant-code",
        web.ConstantCode.add_constant_code,
        name="add-constant-code",
    ),

    path("ticketprefix", web.ConstantCode.get_codes, name="ticket-prefix"),
    path("grades", web.Grade.get_grades, name="grades"),
    re_path(
        r"^edit-grade/(?P<grade_id>[\w-]+)/$",
        web.Grade.edit_grade,
        name="edit-grade",
    ),
    re_path(
        r"^delete-grade/(?P<grade_id>[\w-]+)/$",
        web.Grade.delete_grade,
        name="delete-grade",
    ),
    path("add-grade", web.Grade.add_grade, name="add-grade"),
    path("add-grade-price", web.GradePrice.price_years, name="add-grade-price"),
    path("grade-years", web.GradePrice.grade_years, name="grade-years"),
    # path("grade-prices", web.GradePrice.get_grade_prices, name="grade-prices"),
    re_path(
        r"^add-price/(?P<year_id>[\w-]+)/$",
        web.GradePrice.add_grade_price,
        name="add-price",
    ),
    re_path(
        r"^grade-prices/(?P<year_id>[\w-]+)/$",
        web.GradePrice.get_grade_prices,
        name="grade-prices",
    ),
    re_path(
        r"^edit-grade-price/(?P<price_id>[\w-]+)/$",
        web.GradePrice.edit_grade_price,
        name="edit-grade-price",
    ),
    re_path(
        r"^delete-grade-price/(?P<grade_price_id>[\w-]+)/$",
        web.GradePrice.delete_grade_price,
        name="delete-grade-price",
    ),
    path(
        "in-house-grades", web.InHouseGrade.get_in_house_grades, name="in-house-grades"
    ),
    re_path(
        r"^edit-in-house-grade/(?P<grade_id>[\w-]+)/$",
        web.InHouseGrade.edit_in_house_grade,
        name="edit-in-house-grade",
    ),
    re_path(
        r"^delete-in-house-grade/(?P<grade_id>[\w-]+)/$",
        web.InHouseGrade.delete_in_house_grade,
        name="delete-in-house-grade",
    ),
    path(
        "add-in-house-grade",
        web.InHouseGrade.add_in_house_grade,
        name="add-in-house-grade",
    ),
    path("product-grades", web.ProductGrade.get_product_grades, name="product-grades"),
    path(
        "add-product-grade",
        web.ProductGrade.add_product_grade,
        name="add-product-grade",
    ),
    re_path(
        r"^edit-product-grade/(?P<grade_id>[\w-]+)/$",
        web.ProductGrade.edit_product_grade,
        name="edit-product-grade",
    ),
    re_path(
        r"^delete-product-grade/(?P<grade_id>[\w-]+)/$",
        web.ProductGrade.delete_product_grade,
        name="delete-product-grade",
    ),
    path("crop-years", web.Season.get_seasons, name="crop-years"),
    path("add-crop-year", web.Season.add_season, name="add-crop-year"),
    re_path(
        r"^edit-crop-year/(?P<year_id>[\w-]+)/$",
        web.Season.edit_season,
        name="edit-crop-year",
    ),
    re_path(
        r"^delete-crop-year/(?P<season_id>[\w-]+)/$",
        web.Season.delete_season,
        name="delete-crop-year",
    ),
]

voedsel/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .api import api
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", api.urls),
    path("", include("core.urls")),
    path("", include("auths.urls")),
    path("", include("association.urls")),
    path("market/", include("market.urls", namespace="market")),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("processing/", include("processing.urls", namespace="processing")),
    path("shipment/", include("shipment.urls", namespace="shipment")),
    path("report/", include("report.urls", namespace="report")),
    path("payment/", include("payment.urls", namespace="payment")),
    # path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

core/forms.py
from dataclasses import fields
from django import forms
from .models import *


class Region(forms.ModelForm):
    class Meta:
        model = Region
        fields = ["region_name", "region_code"]


class ConstantCodeForm(forms.ModelForm):
    class Meta:
        model = ConstantCode
        fields = ["code_number",'season']


class GradeForm(forms.ModelForm):
    class Meta:
        model = CropGrade
        fields = ["grade_name"]


class SeasonForm(forms.ModelForm):
    class Meta:
        model = Season
        fields = ["season_name", "start_date", "end_date"]


class InHouseGradeForm(forms.ModelForm):
    class Meta:
        model = InHouseGrade
        fields = ["grade","is_special"]


class ProductGradeForm(forms.ModelForm):
    class Meta:
        model = ProductGrade
        fields = ["grade_name"]


class SeasonForm(forms.ModelForm):
    class Meta:
        model = Season
        fields = ["season_name", "start_date", "end_date"]


class GradePriceForm(forms.ModelForm):
    class Meta:
        model = GradePrice
        fields = ["grade", "price", "season"]

core/views.py
import glob
import os
from http.client import HTTPException
from PIL import Image
from django.shortcuts import render
from core import models
from market.models import Ticket
from ninja.errors import HttpError
import qrcode
from barcode.writer import ImageWriter
from barcode import EAN13, ISBN10, Code128
from ninja.errors import HttpError
from django.http import HttpResponse
from django.template import Context
from django.template.loader import get_template
from voedsel.settings import BASE_DIR
from xhtml2pdf import pisa
from django.conf import settings


# Create your views here.


def generate_qr_code(ticket_number):
    """_generate qr codes with ticket number_

    Args:
        ticket_number (_string_): _description_

    Returns:
        _type_: _description_
    """
    img = qrcode.make(ticket_number)
    location = "static/assets/qr_code/" + ticket_number + ".png"
    img.save(location)
    return location


def generate_bar_code(ticket_number):
    """Generate Bar codes

    Args:
        ticket_number str: string

    Raises:
        HttpError: Internal server error or other errors

    Returns:
        _type_: _description_
    """
    const_number = models.ConstantCode.objects.filter(is_active=True)
    if const_number.count() == 0:
        raise HttpError(
            404, "There is no Constant Number, please Add Constant Number for Barcode"
        )
    number = models.ConstantCode.objects.all()[0].code_number + ticket_number
    bar_code = Code128(number, writer=ImageWriter())
    location = "static/assets/bar_code/" + number
    bar_code.save(
        location,
        options={
            "text_distance": 1,
            "quiet_zone": 2.5,
            "module_height": 6,
            "font_size": 16,
        },
    )
    return location + ".png"


def rotate_bar_code(ticket):
    """Rotate barcode to fit horizontal on tickets"""
    im = Image.open(ticket.bar_code)
    im = im.rotate(90, expand=True)
    location = "static/assets/bar_code/rotated" + ticket.ticket_number + ".png"
    im.save(location)
    Ticket.objects.filter(id=ticket.id).update(rotated_bar_code=location)


def fetch_resources(uri, rel):
    """Fetch settings data"""
    sUrl = settings.STATIC_URL
    sRoot = settings.STATIC_ROOT
    mUrl = settings.MEDIA_URL
    mRoot = settings.MEDIA_ROOT
    if uri.startswith(mUrl):
        path = os.path.join(mRoot, uri.replace(mUrl, ""))
    elif uri.startswith(sUrl):
        path = os.path.join(sRoot, uri.replace(sUrl, ""))
    else:
        return uri
    if not os.path.isfile(path):
        raise Exception("media URI must start with %s or %s" % (sUrl, mUrl))
    return path


def render_to_pdf(path: str, params, filename):
    """Render data to pdf"""
    template_path = path
    context = params
    filename = "media/tickets/" + str(params["tickets"][0].print_request.id) + ".pdf"
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="' + filename + '"'
    template = get_template(template_path)
    html = template.render(context)
    open_file = open(filename, "w+b")
    pisaStatus = pisa.CreatePDF(html, dest=open_file, link_callback=fetch_resources)
    if pisaStatus.err:
        return HttpResponse("We had some errors <pre>" + html + "</pre>")
    open_file.close()
    return filename


def genera_render_to_pdf(path: str, params, filename):
    """Render data to pdf"""
    template_path = path
    context = params
    filename = "media/tickets/" + str(params["tickets"][0].print_request.id) + ".pdf"
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = 'attachment; filename="' + filename + '"'
    template = get_template(template_path)
    html = template.render(context)
    open_file = open(filename, "w+b")
    pisaStatus = pisa.CreatePDF(html, dest=open_file, link_callback=fetch_resources)
    if pisaStatus.err:
        return HttpResponse("We had some errors <pre>" + html + "</pre>")
    open_file.close()
    return filename


def delete_files_in_dir(path):
    """delete all files in particular directory"""
    dir = os.path.join(BASE_DIR, path)
    filelist = glob.glob(os.path.join(dir, "*"))
    for file in filelist:
        os.remove(file)


class Region:
    def __init__(self):
        pass

    def add_region(request, create_region_schema):
        try:
            """Add region with region schema"""
            if type(create_region_schema) != "dict":
                create_region_schema = create_region_schema.dict()

            region = models.Region.objects.create(**create_region_schema)
            region.save()
            return region
        except:
            raise HttpError(503, "Service Unavailable. Please retry later.")

    def get_regions(request):
        """get all regions"""
        try:
            regions = models.Region.objects.filter(is_active=True)
            return regions
        except:
            raise HTTPException(
                data={"status_code": 500, "detail": "Internal Server Error"}
            )

    def delete_region(request, id: str):
        """delete region by region id"""
        try:
            region = models.Region.objects.filter(id=id)
            if region:
                region[0].delete()
                return "Region has successful Deleted"
            raise HTTPException(
                data={
                    "status_code": 404,
                    "detail": "Region Not Found may be was already deleted",
                }
            )

        except:
            raise HTTPException(
                data={"status_code": 500, "detail": "Internal Server Error"}
            )


class CropGrade:
    def __init__(self):
        pass

    def add_crop_grade(request, create_crop_grade_schema):
        try:
            if type(create_crop_grade_schema) != "dict":
                create_crop_grade_schema = create_crop_grade_schema.dict()

            crop_grade = models.CropGrade.objects.create(
                **create_crop_grade_schema, created_by=request.user
            )
            crop_grade.save()
            return crop_grade
        except:
            raise

    def get_crop_grades(request):
        try:
            crop_grades = models.CropGrade.objects.filter(is_active=True)
            return crop_grades
        except:
            raise

    def delete_crop_grade(request, id):
        try:
            crop_grade = models.CropGrade.objects.filter(id=id)
            if crop_grade:
                crop_grade[0].delete()
                return "Crop Grade Successful deleted"
            return "Crop Grade not found may be was already deleted"
        except:
            raise


class CropType:
    def __init__(self):
        pass

    def add_crop_type(request, create_crop_type_schema: None):
        try:
            if type(create_crop_type_schema) != "dict":
                create_crop_type_schema = create_crop_type_schema.dict()
            create_crop_type_schema["crop_seed"] = models.CropSeed.objects.get(
                id=create_crop_type_schema["crop_seed"]
            )
            crop_type = models.CropType.objects.create(**create_crop_type_schema)
            crop_type.save()
            return crop_type
        except:
            raise

    def get_crop_types(request):
        try:
            crop_types = models.CropType.objects.filter(is_active=True)
            return crop_types
        except:
            raise

    def delete_crop_type(request, id: str):
        try:
            crop_type = models.CropType.objects.filter(id=id)
            if crop_type:
                crop_type[0].delete()
                return "Crop Type successful deleted"
            return "Crop Type not found, may be was already deleted"
        except:
            raise


class CropSeed:
    def __init__(self):
        pass

    def add_crop_seed(request, create_crop_seed_schema):
        try:
            if type(create_crop_seed_schema) != "dict":
                create_crop_seed_schema = create_crop_seed_schema.dict()

            crop_seed = models.CropSeed.objects.create(**create_crop_seed_schema)
            crop_seed.save()
            return crop_seed
        except:
            raise

    def get_crop_seeds(request):
        try:
            crop_seeds = models.CropSeed.objects.filter(is_active=True)
            return crop_seeds
        except:
            raise "Internal Server Error"

    def delete_crop_seed(request, id: str):
        try:
            crop_seed = models.CropSeed.objects.filter(id=id)
            if crop_seed:
                crop_seed[0].delete()
                return "Crop Seed successful Deleted"
            return "Crop seed Not found, may be was already Deleted"
        except:
            raise


class Season:
    def __init__(self):
        pass

    def create_season(request, create_season_schema):
        try:
            if type(create_season_schema) != "dict":
                create_season_schema = create_season_schema.dict()

            season = models.Season.objects.create(**create_season_schema)
            season.save()
            return season
        except:
            raise

    def get_seasons(request):
        try:
            seasons = models.Season.objects.filter(is_active=True)
            return seasons
        except:
            raise "Internal Server Error"

    def delete_season(request, id: str):
        try:
            season = models.Season.objects.filter(id=id)
            if season:
                season[0].delete()
                return "Season was successful Deleted"
            return "No season Found, may be was already deleted"
        except:
            raise "Internal Server Error"


class InHouseGrade:
    def __init__(self):
        pass

    def create_in_house_grade(request, create_in_house_grade__schema):
        try:
            if type(create_in_house_grade__schema) != "dict":

templates/core/season/add_season.html
{% extends "common/base.html" %}
{% load static %}

{% block content %}
<div id="content-page" class="content-page">
   <div class="container-fluid">
    <div class="row">
     <div class="col-8">
        <div class="iq-card">
            <div class="iq-card">
                <div class="iq-card-header d-flex justify-content-between row">
                   <div class="iq-header-title col-12">
                      <h4 class="card-title">{% if form %} Edit {% else %}Add  {% endif %} Crop Year</h4>
                   </div>
                   {% if message %}
                   <div class="alert alert-danger col-6 ml-4" role="alert">
                     <div class="iq-alert-icon">
                       <i class="ri-information-line"></i>
                    </div>
                    <div class="iq-alert-text alert-danger">{{message}}</div>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                     <i class="ri-close-line text-danger"></i>
                     </button>
                 </div>
                 {% endif %}
                </div>
                <div class="iq-card-body">

                    <form {% if form %} action="{% url 'core:edit-crop-year' year_id=form.id %}" {% else %}  action="{% url 'core:add-crop-year'%}" {% endif %} method="post">
                      {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-12">
                            <label for="text">Crop year Name:</label>
                            <input type="text" class="form-control" {% if form %} value="{{ form.season_name }}" {% endif %}  name="season_name">
                         </div>
                         <div class="form-group col-6">
                            <label for="text">Start On:</label>
                            <input type="date" class="form-control" {% if form %} value="{{form.start_date|date:"Y-m-d" }}" {% endif %} name="start_date">
                         </div>
                         <div class="form-group col-6">
                            <label for="text">End On:</label>
                            <input type="date" class="form-control" {% if form %} value="{{ form.end_date|date:"Y-m-d" }}" {% endif %} name="end_date">
                         </div>
                         <div class="col-12">
                            <button type="submit" class="btn btn-primary float-right" >{% if form %} Save  {% else %} Create {% endif %}</button>
                         </div>
                    </div>
                   </form>
                </div>
             </div>
        </div>
       </div>
       </div>
      </dev>

{% endblock %}

templates/core/season/seasons.html
{% extends "common/base.html" %}
{% load static %}

{% block content %}
<div id="content-page" class="content-page">
<div class="container-fluid">
<div class="row">
<div class="col-lg-8">
    <div class="iq-card iq-card-block iq-card-stretch iq-card-height">
       <div class="iq-card-header d-flex justify-content-between">
          <div class="iq-header-title">
             <h4 class="card-title">{{header}}</h4>
          </div>
          <div class="iq-card-header-toolbar d-flex align-items-center">
             <div class="dropdown">
                <span >
                <a href="{% url 'core:add-crop-year'%}" class="btn btn-primary la la-plus-rounded">Add</a>
                </span>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton5">
                   <a class="dropdown-item" href="#"><i class="ri-eye-fill mr-2"></i>View</a>
                   <a class="dropdown-item" href="#"><i class="ri-delete-bin-6-fill mr-2"></i>Delete</a>
                   <a class="dropdown-item" href="#"><i class="ri-pencil-fill mr-2"></i>Edit</a>
                   <a class="dropdown-item" href="#"><i class="ri-printer-fill mr-2"></i>Print</a>
                   <a class="dropdown-item" href="#"><i class="ri-file-download-fill mr-2"></i>Download</a>
                </div>
             </div>
          </div>
       </div>
       <div class="iq-card-body">
          <div class="table-responsive">
             <table class="table mb-0 tbl">
                <thead class="thead-light">
                   <tr>
                      <th scope="col">Crop Year</th>
                      <th scope="col">Start Date</th>
                      <th scope="col">End Date</th>
                      <th scope="col">Action</th>
                   </tr>
                </thead>
                <tbody>
                    {% for season in page_obj %}
                   <tr>
                      <td>{{season.season_name}}</td>
                      <td>{{season.start_date}}</td>
                      <td>{{season.end_date}}</td>
                      <td>
                        <a href="{% url 'core:edit-crop-year' year_id=season.id %}" class="badge badge-pill badge-info">Edit</a>
                        <div class="badge badge-pill badge-danger" data-toggle="modal" data-target="#delete{{season.id}}">{% if season.is_active %}Deactivate{% else %} Activate {% endif %}</div>
                        <div id="delete{{season.id}}" class="modal top" tabindex="-1">
                           <div class="modal-dialog modal-sm ">
                               <div class="modal-content bg-white-300">
                                   <div class="modal-header">
                                    <center><h5 class="modal-title text-danger" align="center">Warning</h5></center>
                                       <button type="button" class="close" data-dismiss="modal">&times;</button>

                                   </div>
                                   <div class="modal-body">
                                       <center><i class="icon-help icon-4x mb-3 mt-1 " style="height: 40px;"></i>
                                          <i class="la la-question-circle text-danger" style="font-size:64px"></i>
                                           <h6 class="font-weight-semibold">{% if season.is_active %}Deactivate?{% else %} Activate? {% endif %}</h6>
                                       </center>
                                   </div>
                                   <div class="modal-footer">
                                       <button type="button" class="btn btn-danger text-white" data-dismiss="modal">Cancel</button>
                                       <a href="{% url 'core:delete-crop-year' season_id=season.id %}"><button type="button"
                                               class="btn bg-success">Yes</button></a>
                                   </div>
                               </div>
                           </div>
                       </div>
                     </td>
                   </tr>
                   {% endfor %}
                </tbody>
             </table>
          </div>
       </div>
    </div>
 </div>
</div>

{% endblock content %}
    {% block js %}
{% include 'common/datatable.html' %}
   <script type="text/javascript">
    $(document).ready(function() {
        $('.tbl').DataTable( {
        destroy: true,
        paging:false,
        ordering:false,
        dom: 'Bfrtip',

        buttons: [
         'excel',
         {   text: '<i class="fa fa-plus-square-o"></i>ACTIVE',
                    className: 'btn btn-primary btn-p',
                     action: function (e, dt, node, config)
                        {
                            var url = "{% url 'core:crop-years' %}";
                          window.location=url;

                        }
                },

         { text: '<i class="fa fa-plus-square-o"></i>INACTIVE',
                    className: 'btn btn-danger btn-d',
                     action: function (e, dt, node, config)
                        {
                            var url = "{% url 'core:crop-years' %}?status=0";
                          window.location=url;

                        }
                }
        ]
    } );
    });
</script>
{% endblock %}