core/urls.py
from unicodedata import name
from django.urls import path, re_path
from core.api import add_region, add_season

from core.models import Region, Season
from . import web

app_name = "core"
urlpatterns = [
    path("", web.Dashboard.index, name="dashboard"),
    path("seasons", web.Season.get_seasons, name="seasons"),
    path("add-season", web.Season.add_season, name="add-season"),
    path("add-region", web.Region.add_region, name="add-region"),
    path("regions", web.Region.get_regions, name="regions"),
    path("inactive-regions", web.Region.get_inactive_regions, name="inactive_regions"),
    re_path(
        r"^edit-region/(?P<region_id>[\w-]+)/$",
        web.Region.edit_region,
        name="edit-region",
    ),
    re_path(
        r"^delete-region/(?P<region_id>[\w-]+)/$",
        web.Region.delete_region,
        name="delete-region",
    ),
    path(
        "add-constant-code",
        web.ConstantCode.add_constant_code,
        name="add-constant-code",
    ),

    path("ticketprefix", web.ConstantCode.get_codes, name="ticket-prefix"),
    path("grades", web.Grade.get_grades, name="grades"),
    re_path(
        r"^edit-grade/(?P<grade_id>[\w-]+)/$",
        web.Grade.edit_grade,
        name="edit-grade",
    ),
    re_path(
        r"^delete-grade/(?P<grade_id>[\w-]+)/$",
        web.Grade.delete_grade,
        name="delete-grade",
    ),
    path("add-grade", web.Grade.add_grade, name="add-grade"),
    path("add-grade-price", web.GradePrice.price_years, name="add-grade-price"),
    path("grade-years", web.GradePrice.grade_years, name="grade-years"),
    # path("grade-prices", web.GradePrice.get_grade_prices, name="grade-prices"),
    re_path(
        r"^add-price/(?P<year_id>[\w-]+)/$",
        web.GradePrice.add_grade_price,
        name="add-price",
    ),
    re_path(
        r"^grade-prices/(?P<year_id>[\w-]+)/$",
        web.GradePrice.get_grade_prices,
        name="grade-prices",
    ),
    re_path(
        r"^edit-grade-price/(?P<price_id>[\w-]+)/$",
        web.GradePrice.edit_grade_price,
        name="edit-grade-price",
    ),
    re_path(
        r"^delete-grade-price/(?P<grade_price_id>[\w-]+)/$",
        web.GradePrice.delete_grade_price,
        name="delete-grade-price",
    ),
    path(
        "in-house-grades", web.InHouseGrade.get_in_house_grades, name="in-house-grades"
    ),
    re_path(
        r"^edit-in-house-grade/(?P<grade_id>[\w-]+)/$",
        web.InHouseGrade.edit_in_house_grade,
        name="edit-in-house-grade",
    ),
    re_path(
        r"^delete-in-house-grade/(?P<grade_id>[\w-]+)/$",
        web.InHouseGrade.delete_in_house_grade,
        name="delete-in-house-grade",
    ),
    path(
        "add-in-house-grade",
        web.InHouseGrade.add_in_house_grade,
        name="add-in-house-grade",
    ),
    path("product-grades", web.ProductGrade.get_product_grades, name="product-grades"),
    path(
        "add-product-grade",
        web.ProductGrade.add_product_grade,
        name="add-product-grade",
    ),
    re_path(
        r"^edit-product-grade/(?P<grade_id>[\w-]+)/$",
        web.ProductGrade.edit_product_grade,
        name="edit-product-grade",
    ),
    re_path(
        r"^delete-product-grade/(?P<grade_id>[\w-]+)/$",
        web.ProductGrade.delete_product_grade,
        name="delete-product-grade",
    ),
    path("crop-years", web.Season.get_seasons, name="crop-years"),
    path("add-crop-year", web.Season.add_season, name="add-crop-year"),
    re_path(
        r"^edit-crop-year/(?P<year_id>[\w-]+)/$",
        web.Season.edit_season,
        name="edit-crop-year",
    ),
    re_path(
        r"^delete-crop-year/(?P<season_id>[\w-]+)/$",
        web.Season.delete_season,
        name="delete-crop-year",
    ),
]

shipment/urls.py
from django.urls import path, re_path
from . import web

app_name = "shipment"
urlpatterns = [

    path("tcomapanies", web.ListTransportCompany.as_view(), name="tcompanies"),
    path("add-tcomapny", web.AddTransportCompany.as_view(), name="add_tcompany"),
    re_path(r"(?P<pk>[\w-]+)/Atcomapny", web.ActivateDeactivateCompany.as_view(), name="active_tcompanies"),

    re_path(r"(?P<pk>[\w-]+)/tcomapny", web.UpdateTransportCompany.as_view(), name="update_tcompanies"),
    path("drivers", web.Driver.get_drivers, name="drivers"),
    path("add-driver", web.Driver.add_driver, name="add-driver"),
    re_path(
        r"^edit-driver/(?P<driver_id>[\w-]+)/$",
        web.Driver.edit_driver,
        name="edit-driver",
    ),
    re_path(
        r"^delete-driver/(?P<driver_id>[\w-]+)/$",
        web.Driver.delete_driver,
        name="delete-driver",
    ),
    path("tracks", web.Track.get_tracks, name="tracks"),
    path("add-tracks", web.Track.add_track, name="add-track"),
    re_path(
        r"^edit-track/(?P<track_id>[\w-]+)/$",
        web.Track.edit_track,
        name="edit-track",
    ),
    re_path(
        r"^delete-track/(?P<track_id>[\w-]+)/$",
        web.Track.delete_track,
        name="delete-track",
    ),
    path(
        "add-warehouse-shipment",
        web.Shipment.add_warehouse_shipment,
        name="add-warehouse-shipment",
    ),
    path(
        "warehouse-shipments",
        web.Shipment.get_warehouse_shipments,
        name="warehouse-shipments",
    ),
    re_path(
        r"^edit-warehouse-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.edit_warehouse_shipment,
        name="delete-warehouse-shipment",
    ),
    re_path(
        r"^delete-warehouse-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.edit_warehouse_shipment,
        name="delete-warehouse-shipment",
    ),
    path(
        "add-warehouse-processing-shipment",
        web.Shipment.add_warehouse_processing_shipment,
        name="add-warehouse-processing-shipment",
    ),
    path(
        "warehouse-processing-shipments",
        web.Shipment.get_warehouse_processing_shipments,
        name="warehouse-processing-shipments",
    ),
    re_path(
        r"^delete-warehouse-processing-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.delete_warehouse_processing_shipment,
        name="delete-warehouse-processing-shipment",
    ),
    re_path(
        r"^edite-warehouse-processing-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.edit_warehouse_processing_shipment,
        name="edit-warehouse-processing-shipment",
    ),
    path(
        "add-market-warehouse-shipment",
        web.Shipment.add_market_warehouse_shipment,
        name="add-market-warehouse-shipment",
    ),
    path(
        "market-warehouse-shipments",
        web.Shipment.get_market_warehouse_shipments,
        name="market-warehouse-shipments",
    ),
    re_path(
        r"^edit-market-warehouse-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.edit_market_warehouse_shipment,
        name="edit-market-warehouse-shipment",
    ),

    ####SHIPMENT REFRESH
    re_path(
        r"^refmarket_warehouse_shipment_refresh/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.market_warehouse_shipment_refresh,
        name="market_warehouse_shipment_refresh",
    ),

    re_path(
        r"^delete-market-warehouse-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.delete_market_warehouse_shipment,
        name="delete-market-warehouse-shipment",
    ),
    path(
        "add-market-processing-shipment",
        web.Shipment.add_market_processing_shipment,
        name="add-market-processing-shipment",
    ),
    path(
        "market-processing-shipments",
        web.Shipment.get_market_processing_shipments,
        name="market-processing-shipments",
    ),
    re_path(
        r"^edit-market-processing-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.edit_market_processing_shipment,
        name="edit-market-processing-shipment",
    ),
    re_path(
        r"^delete-market-processing-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.delete_market_processing_shipment,
        name="delete-market-processing-shipment",
    ),
    path(
        "add-sales-shipment", web.Shipment.add_sales_shipment, name="add-sales-shipment"
    ),
    path("sales-shipments", web.Shipment.get_sales_shipments, name="sales-shipments"),
    re_path(
        r"^edit-sales-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.edit_sales_shipment,
        name="edit-sales-shipment",
    ),
    re_path(
        r"^delete-sales-shipment/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.delete_sales_shipment,
        name="delete-sales-shipment",
    ),
    re_path(
        r"^warehouse-details/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.get_warehouse_details,
        name="warehouse-details",
    ),
    re_path(
        r"^warehouse-pricessing-details/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.get_warehouse_processing_details,
        name="warehouse-processing-details",
    ),
    re_path(
        r"^market-warehouse-details/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.get_market_warehouse_details,
        name="market-warehouse-details",
    ),
    re_path(
        r"^market-processing-details/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.get_market_processing_details,
        name="market-processing-details",
    ),
    re_path(
        r"^sales-details/(?P<shipment_id>[\w-]+)/$",
        web.Shipment.get_sales_details,
        name="sales-details",
    ),
    re_path(r"^new-custom-shipment$",web.AddGeneralShipmentView.as_view(),name="new-custom-shipment",),
    
    
    re_path(r"^(?P<pk>[\w-]+)/update-custom-shipment$",web.UpdateGeneralShipmentView.as_view(),name="edit-custom-shipment",),
    re_path(r"^(?P<pk>[\w-]+)/delete-custom-shipment$",web.DeleteGeneralShipmentView.as_view(),name="delete-custom-shipment",),
    re_path(r"^(?P<pk>[\w-]+)/detail-custom-shipment$",web.DetailGeneralShipmentView.as_view(),name="detail-custom-shipment",),
    re_path(r"^(?P<pk>[\w-]+)/send-email$",web.FileSendEmailToProcessing.as_view(),name="send_shipment_email",),

    ####EMAIL RECEIVERS
    re_path(r"^(?P<pk>[\w-]+)/delemaireceiver$",web.DeleteEmailReceiversView.as_view(),name="delete-receiver",),
    re_path(r"^addemaireceiver$",web.AddEmailReceiverView.as_view(),name="add-receiver",),
    re_path(r"^emailfilereceivers$",web.ListEmailReceiversView.as_view(),name="list-email-receivers",),
    
    
    re_path(r"^(?P<pk>[\w-]+)/remove-bale-custom-shipment$",web.RemoveBaleonGeneralShipmentBaleView.as_view(),name="remove-bale-shipment",),
    
    re_path(r"^assignno$",web.ChangeGeneralShipmentNoView.as_view(),name="asignno",),

    re_path(r"^list-g-shipment$",web.ListGeneralShipmentView.as_view(),name="list-custom-shipment",),
    re_path(r"^done-list-g-shipment$",web.ListGeneralShipmentDoneView.as_view(),name="done-list-custom-shipment",),
    
    re_path(r"^(?P<pk>[\w-]+)/file-kiwandani$",web.FileForImporting.as_view(),name="file-kiwandani",),
    re_path(r"^(?P<pk>[\w-]+)/end-shipment$",web.EndShipments.as_view(),name="end_tshipment",),
    re_path(r"^(?P<pk>[\w-]+)/open-shipment$",web.OpenShipments.as_view(),name="open_tshipment",),
    
    re_path(r"^(?P<pk>[\w-]+)/delete-line$",web.DeleteshiingTicket.as_view(),name="delete_line",),
    re_path(r"^shipmentvalue$",web.RefreshshiingValue.as_view(),name="refresh_shipvalue",),
    #IMPORT NOW
    re_path(r"^sync-processing-receing-report",web.IMPORT.process_uploaded_file_now,name="sync-processing",),
    re_path(r"^large-csv-import",web.process_csv,name="large_csv",),

    
    



]

voedsel/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .api import api
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", api.urls),
    path("", include("core.urls")),
    path("", include("auths.urls")),
    path("", include("association.urls")),
    path("market/", include("market.urls", namespace="market")),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("processing/", include("processing.urls", namespace="processing")),
    path("shipment/", include("shipment.urls", namespace="shipment")),
    path("report/", include("report.urls", namespace="report")),
    path("payment/", include("payment.urls", namespace="payment")),
    # path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

shipment/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError


class DriverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = ["full_name", "phone_number", "license",'company']

class CompanyForm(forms.ModelForm):
    class Meta:
        model = TransportCompany
        fields = ["name", "address"]

    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-title'

        self.fields['address'].widget.attrs['rows'] = '2'
        self.fields['address'].widget.attrs['cols'] = '12'






class TrackForm(forms.ModelForm):
    class Meta:
        model = Track
        fields = ["track_name", "reg_number", "document_number",'company']


class WarehouseShipmentForm(forms.ModelForm):
    class Meta:
        model = WarehouseShipment
        fields = [
            "from_warehouse",
            "to_warehouse",
            "personnel",
            "personnel_receiver",
            "track",
            "driver",
            "shipment_date",
        ]


class MarketProcessingShipmentForm(forms.ModelForm):
    class Meta:
        model = MarketProcessingShipment
        fields = [
            "market",
            "processing_centre",
            "personnel",
            "market_request",
            "personnel_receiver",
            "track",
            "driver",
            "shipment_date",
        ]


class WarehouseProcessingShipmentForm(forms.ModelForm):
    class Meta:
        model = WarehouseProcessingShipment
        fields = [
            "warehouse",
            "processing_centre",
            "personnel",
            "personnel_receiver",
            "track",
            "driver",
            "shipment_date",
        ]


class MarketWarehouseShipmentForm(forms.ModelForm):
    class Meta:
        model = MarketWarehouseShipment
        fields = [
            "market",
            "warehouse",
            "track",
            "personnel",
            "market_request",
            "personnel_receiver",
            "driver",
            "shipment_date",
        ]


class SalesShipmentForm(forms.ModelForm):
    class Meta:
        model = SalesShipment
        fields = [
            "processing_centre",
            "sales_location",
            "track",
            "driver",
            "personnel",
            "shipment_date",
        ]
class GeneralShipmentForm(forms.ModelForm):
    shipment_date=forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    class Meta:
        model = GeneralShipment
        fields = ['from_warehouse', 'to_warehouse', 'transporter', 'receiver', 'driver', 'track', 'shipment_date']

    def __init__(self, *args, **kwargs):
        super(GeneralShipmentForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-title'
      
        self.fields['from_warehouse'].widget.attrs['class'] = 'select2'
        self.fields['to_warehouse'].widget.attrs['class'] = 'select2'
        self.fields['transporter'].widget.attrs['class'] = 'select2'
        self.fields['driver'].widget.attrs['class'] = 'select2'
        self.fields['track'].widget.attrs['class'] = 'select2'
        self.fields['receiver'].widget.attrs['class'] = 'select2'

    def clean(self):
        clean_data=super(GeneralShipmentForm, self).clean()
        if clean_data['from_warehouse'] == clean_data['to_warehouse']:
            raise ValidationError('Cannote be shiped to the same warehouse')

class GeneralEmailForm(forms.ModelForm):
    class Meta:
        model = SendingShipmentEmail
        fields = ['name', 'email']

    def __init__(self, *args, **kwargs):
        super(GeneralEmailForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-title'

templates/shipment/custom/add_email.html
{% extends "common/base.html" %}
{% load static %}

{% block content %}
{% load crispy_forms_tags %}
<div id="content-page" class="content-page">
   <div class="container-fluid">
    <div class="row">
     <div class="col-12">
        <div class="iq-card">
            <div class="iq-card">
                <div class="iq-card-header d-flex justify-content-between row">
                   <div class="iq-header-title col-12">
                      <h4 class="card-title">EMAIL RECEIVER</h4>
                   </div>
                          {% if form.errors or error1 %}
                   <div class="alert alert-danger col-10 ml-4" role="alert">
                     <div class="iq-alert-icon">
                       <i class="ri-information-line"></i>
                    </div>
                    <div class="iq-alert-text alert-danger">
                        <p>There were some errors in the information you entered. Please correct the following:</p>
                        {{ form.non_field_errors }}
                        <ul>
                            {% for field in form %}
                                {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                            {% endfor %}
                        </ul>
                    {% if error1 %}
                     <span class="">
                         {{error1}}
                     </span>
                    {% endif %}


                    </div>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                     <i class="ri-close-line text-danger"></i>
                     </button>
                 </div>
                 {% endif %}
                </div>
                <div class="iq-card-body">

                    <form action="" method="post">
                      {% csrf_token %}
                    <div class="row">
                         <div class="form-group col-6">
                           {{form.name|as_crispy_field}}
                        </div>
                         <div class="form-group col-6">
                           {{form.email|as_crispy_field}}
                        </div>
                         
               

                         <div class="col-12">
                            <button type="submit" class="btn btn-primary float-right" >{% if form %} Save  {% else %} Create {% endif %}</button>
                         </div>
                    </div>
                   </form>
                </div>
             </div>
        </div>
       </div>
       </div>
      </dev>

{% endblock %}

templates/shipment/custom/general_shipment.html
{% extends "common/base.html" %}
{% load static %}
{% load humanize %}

{% block content %}
<div id="content-page" class="content-page">
<div class="container-fluid">
<div class="row">
<div class="col-lg-12">
    <div class="iq-card iq-card-block iq-card-stretch iq-card-height">
       <div class="iq-card-header d-flex justify-content-between">
          <div class="iq-header-title">
             <h4 class="card-title">{{header}}</h4>
          </div>
          <div class="iq-card-header-toolbar d-flex align-items-center">
             <div class="dropdown">
                <span >
                <a href="{% url 'shipment:new-custom-shipment'%}" class="btn btn-primary la la-plus-rounded">Add</a>
                </span>

             </div>
          </div>
       </div>
       <div class="iq-card-body">
         <div class="row col-md-12">
         <div class="col-md-3">
             <table class="table table-bordered">
               <tr>
                  <th>SH#</th>
                  <th>BALES</th>
                    <th>KGS</th>
               </tr>
               {% for total in summaries %}
               <tr>
                  <td {% if total.is_closed %} bgcolor="#EAECEE" {% endif %}>{{total.shipmentno}}</td>
                  <td  {% if total.is_closed %} bgcolor="#EAECEE" {% endif %}>{{total.bls|intcomma}}</td>
                  <td  {% if total.is_closed %} bgcolor="#EAECEE" {% endif %}>{{total.summ|floatformat:2|intcomma}}</td>
               </tr>
               {% endfor %}
               <tr>
                  <td bgcolor="#e5e535"><b>TOTAL</b></td>
                  <td bgcolor="#e5e535"><b>{{totals.bls|intcomma}}</b></td>
                  <td bgcolor="#e5e535"><b>{{totals.summ|floatformat:2|intcomma}}</b></td>
               </tr>
             </table>
         </div>
          <div class="col-md-9">
          <div class="table-responsive">
             <table class="table mb-0 tbl">
                <thead class="thead-light">
                   <tr>
                        <th scope="col">Number</th>
                      <th scope="col">From</th>
                      <th scope="col">To</th>

                      <!-- <th scope="col">Driver</th> -->
                      <th scope="col">Track</th>
                      <th scope="col">Transporter</th>
                      <!-- <th scope="col">Receiver</th> -->
                      <th scope="col">Shipment Date</th><!-- 
                      <th scope="col">Shipment Status</th> -->
                       <th></th>

                      <th scope="col" class="text-center">Action</th>
                   </tr>
                </thead>
                <tbody>

                    {% for shipment in lists%}
                   <tr>
                        <td>{{shipment.shipment_number}}</td>
                      <td>{{shipment.from_warehouse}}</td>
                       <td>{{shipment.to_warehouse}}</td>

                     <!--  <td>{{shipment.driver.full_name}}</td> -->
                      <td>{{shipment.track.track_name}}</td>
                      <td>{{shipment.transporter.full_name}}</td>
                      <!-- <td>{{shipment.receiver.full_name}}</td> -->
                      <td>
                        {% if shipment.shipment_date %}
                        {{shipment.shipment_date|date:'m/d/Y'}}
                        {% else %}
                        -
                        {% endif %}
                       </td>

                   <!--   <td>
                        {% if not shipment.shipment_status %}
                        -
                        {% else %}
                        {{shipment.shipment_status}}
                        {% endif %}
                       </td> -->
                       <td><div class="badge badge-pill badge-success"><a href="{% url 'shipment:detail-custom-shipment' pk=shipment.id %}"><i class="la la-th-large"></i> Details</a></div></td>
                      <td class="text-center">

                          <a href="{% url 'shipment:edit-custom-shipment' pk=shipment.id %}" class="badge badge-pill badge-info"><i class="las la-pen-square"></i></a>

                            <!-- <a href="javascript:;" onclick="modal_common('{% url 'shipment:delete-custom-shipment' pk=shipment.id %}');" class="badge badge-pill badge-danger"><i class="las la-trash"></i></a> -->

                     </td>
                   </tr>
                   {% endfor %}
                </tbody>
             </table>
          </div>
       </div>
    </div>
       </div>
    </div>
 </div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>

  <script type="text/javascript">
    $(document).ready(function() {
        $('.tbl').DataTable( {
         dom: 'Bfrtip',
        ordering:false,
        paging:false,
        buttons:[
         'excelHtml5',
            'csv',
            {
                    text: 'CURRENT',
                    className: 'orange, btn btn-primary',
                     action: function (e, dt, node, config)
                        {

                          window.location="{% url 'shipment:list-custom-shipment' %}"

                        }
                },
             {
                    text: 'COMPLETED',
                    className: 'orange, btn btn-secondary',
                     action: function (e, dt, node, config)
                        {

                          window.location="{% url 'shipment:done-list-custom-shipment' %}"

                        }
                }
        ]

    } );
    });
</script>
{% endblock %}

templates/shipment/custom/list_email_receivers.html
{% extends "common/base.html" %}
{% load static %}
{% load humanize %}

{% block content %}
<div id="content-page" class="content-page">
<div class="container-fluid">
<div class="row">
<div class="col-lg-12">
    <div class="iq-card iq-card-block iq-card-stretch iq-card-height">
       <div class="iq-card-header d-flex justify-content-between">
          <div class="iq-header-title">
             <h4 class="card-title">Emails for Shipments</h4>
          </div>
          <div class="iq-card-header-toolbar d-flex align-items-center">
             <div class="dropdown">
                <span >
                <a href="{% url 'shipment:add-receiver' %}" class="btn btn-primary la la-plus-rounded">Add</a>
                </span>

             </div>
          </div>
       </div>
       <div class="iq-card-body">
         <div class="row col-md-12">
         <div class="col-md-3">
            
         </div>
          <div class="col-md-9">
          <div class="table-responsive">
             <table class="table mb-0 tbl">
                <thead class="thead-light">
                   <tr>
                        <th scope="col">SN</th>
                      <th scope="col">NAME</th>
                      <th scope="col">EMAIL</th>
                      <th scope="col" class="text-center">Action</th>
                   </tr>
                </thead>
                <tbody>

                    {% for em in lists %}
                   <tr>
                        <td>{{forloop.counter}}</td>
                      <td>{{em.name}}</td>
                      <td>{{em.email}}</td>

                    
                      
                      <td class="text-center"> <a href="javascript:;" onclick="modal_common('{% url 'shipment:delete-receiver' pk=em.id %}');" class="badge badge-pill badge-danger"><i class="las la-trash"></i></a> 

                     </td>
                   </tr>
                   {% endfor %}
                </tbody>
             </table>
          </div>
       </div>
    </div>
       </div>
    </div>
 </div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>

  <script type="text/javascript">
    $(document).ready(function() {
        $('.tbl').DataTable( {
         dom: 'Bfrtip',
        ordering:false,
        paging:false,
        buttons:[
            'csv',
         
        ]

    } );
    });
</script>
{% endblock %}